name: Deploy v5 Preview

on:
  push:
    branches:
      - v4

env:
  THEME_NAME: its-theme

permissions:
  contents: read
  deployments: write
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-slim
    timeout-minutes: 30
    name: v5 Build
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.SUBMODULES_PAT }}
          submodules: recursive
      # - name: Setup Bun
      #   uses: oven-sh/setup-bun@v2
      #   with:
      #     bun-version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Replace password placeholder
        env:
          PASSWORD: ${{ secrets.QUARTZ_PASSWORD }}
        run: find ./content -type f -print0 | xargs -0 sed -i "s/HIDE_FROM_PLAYERS/${PASSWORD}/g"
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Cache Quartz plugins
        uses: actions/cache@v5
        with:
          path: .quartz/plugins
          key: ${{ runner.os }}-plugins-${{ hashFiles('**/quartz.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-plugins-
      - name: Install dependencies
        run: npm ci # bun ci
      - name: Install Quartz plugins
        run: npx quartz plugin install # bun run -b quartz/bootstrap-cli.mjs plugin install -v
      - name: Check types and style
        run: npm run check # bun run check
      - name: Build Quartz
        run: npx quartz build --bundleInfo # bun run -b quartz/bootstrap-cli.mjs build --bundleInfo -v
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
